///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApplyModel {
/*
{
  "userId": 0,
  "advertId": 0,
  "appDate": "2024-08-01T08:39:06.710Z",
  "appLetter": "string"
} 
*/

  int? userId;
  int? advertId;
  String? appDate;
  String? appLetter;
  bool? uisEmailVerified;
  ApplyModel({
    this.userId,
    this.advertId,
    this.appDate,
    this.appLetter,
    this.uisEmailVerified
  });
  ApplyModel.fromJson(Map<String, dynamic> json) {
    userId = json['userId']?.toInt();
    advertId = json['advertId']?.toInt();
    appDate = json['appDate']?.toString();
    appLetter = json['appLetter']?.toString();
    uisEmailVerified = json['uisEmailVerified'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['advertId'] = advertId;
    data['appDate'] = appDate;
    data['appLetter'] = appLetter;
    data['uisEmailverified'] = uisEmailVerified;
    return data;
  }
}
